---
# =============================================================================
# WezTerm Installation
# =============================================================================

- name: Install WezTerm (macOS)
  homebrew_cask:
    name: wezterm
    state: present
  when: ansible_os_family == "Darwin"
  become: false

- name: Check if WezTerm is already installed (Linux)
  command: wezterm --version
  register: wezterm_check
  failed_when: false
  changed_when: false
  when: ansible_os_family != "Darwin"

- name: Install WezTerm via official repository (Ubuntu/Debian)
  block:
    - name: Add WezTerm GPG key
      shell: |
        curl -fsSL https://apt.fury.io/wez/gpg.key | sudo gpg --yes --dearmor -o /usr/share/keyrings/wezterm-fury.gpg
      args:
        creates: /usr/share/keyrings/wezterm-fury.gpg

    - name: Add WezTerm repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *"
        state: present
        filename: wezterm
      become: true

    - name: Install WezTerm
      apt:
        name: wezterm
        state: present
        update_cache: yes
      become: true
  when: ansible_os_family == "Debian" and wezterm_check.rc != 0

- name: Install Nerd Fonts (macOS)
  homebrew:
    name:
      - font-jetbrains-mono-nerd-font
      - font-hack-nerd-font
    state: present
  when: ansible_os_family == "Darwin"
  become: false

- name: Ensure fonts directory exists (Linux)
  file:
    path: "{{ font_install_path }}"
    state: directory
    mode: '0755'
  when: ansible_os_family != "Darwin"

- name: Download JetBrainsMono Nerd Font (Linux)
  get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ nerd_font_version }}/JetBrainsMono.zip"
    dest: "/tmp/JetBrainsMono.zip"
  when: ansible_os_family != "Darwin"

- name: Extract JetBrainsMono Nerd Font (Linux)
  unarchive:
    src: "/tmp/JetBrainsMono.zip"
    dest: "{{ font_install_path }}"
    remote_src: yes
  when: ansible_os_family != "Darwin"

- name: Update font cache (Linux)
  command: fc-cache -fv
  when: ansible_os_family != "Darwin"

- name: Display WezTerm installation status
  debug:
    msg: |
      WezTerm terminal emulator installed successfully!
      JetBrainsMono Nerd Font installed.

      Your wezterm.lua config is already in place from dotfiles.
      It includes cross-platform OS detection for macOS, Linux, and WSL.

      Launch WezTerm and enjoy!
