---
# =============================================================================
# macOS-Specific Tools Installation
# =============================================================================

- name: Ensure this only runs on macOS
  fail:
    msg: "This role is only for macOS (Darwin)"
  when: ansible_os_family != "Darwin"

- name: Check if Homebrew is installed
  stat:
    path: /opt/homebrew/bin/brew
  register: homebrew_check

- name: Install Homebrew
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: not homebrew_check.stat.exists

- name: Add Homebrew to PATH for this session
  set_fact:
    ansible_env: "{{ ansible_env | combine({'PATH': '/opt/homebrew/bin:' + ansible_env.PATH}) }}"
  when: not homebrew_check.stat.exists

# =============================================================================
# Install macOS Window Manager and Tools
# =============================================================================

- name: Install aerospace (tiling window manager)
  homebrew:
    name: nikitabobko/tap/aerospace
    state: present
  when: macos_window_manager == "aerospace"
  become: false

- name: Install ice bar (menu bar manager)
  homebrew:
    name: jordanbaird-ice
    state: present
  when: macos_menu_bar == "ice"
  become: false

# =============================================================================
# Install from Brewfile
# =============================================================================

- name: Check if Brewfile exists
  stat:
    path: "{{ brewfile_path }}"
  register: brewfile_exists

- name: Install packages from Brewfile
  shell: brew bundle --file="{{ brewfile_path }}"
  args:
    chdir: "{{ ansible_user_dir }}"
  when: brewfile_exists.stat.exists
  ignore_errors: yes

# =============================================================================
# Apply aerospace configuration
# =============================================================================

- name: Ensure aerospace config directory exists
  file:
    path: "{{ ansible_user_dir }}/.config/aerospace"
    state: directory
    mode: '0755'

- name: Check if aerospace config exists in dotfiles
  stat:
    path: "{{ ansible_user_dir }}/.config/aerospace/aerospace.toml"
  register: aerospace_config

- name: Display aerospace status
  debug:
    msg: |
      aerospace config found at ~/.config/aerospace/aerospace.toml
      Configuration already in place from dotfiles.
  when: aerospace_config.stat.exists

# =============================================================================
# macOS System Preferences (Dock)
# =============================================================================

- name: Configure Dock preferences
  block:
    - name: Set Dock orientation to left
      osx_defaults:
        domain: com.apple.dock
        key: orientation
        type: string
        value: left
      notify: Restart Dock

    - name: Set Dock minimize effect to suck
      osx_defaults:
        domain: com.apple.dock
        key: mineffect
        type: string
        value: suck
      notify: Restart Dock

    - name: Enable Dock autohide
      osx_defaults:
        domain: com.apple.dock
        key: autohide
        type: int
        value: 1
      notify: Restart Dock

    - name: Set Dock autohide delay to 0
      osx_defaults:
        domain: com.apple.dock
        key: autohide-delay
        type: float
        value: 0
      notify: Restart Dock

    - name: Set Dock autohide animation time
      osx_defaults:
        domain: com.apple.dock
        key: autohide-time-modifier
        type: float
        value: 1
      notify: Restart Dock

    - name: Enable Dock magnification
      osx_defaults:
        domain: com.apple.dock
        key: magnification
        type: int
        value: 1
      notify: Restart Dock

    - name: Set Dock tile size
      osx_defaults:
        domain: com.apple.dock
        key: tilesize
        type: int
        value: 32
      notify: Restart Dock

    - name: Set Dock magnified icon size
      osx_defaults:
        domain: com.apple.dock
        key: largesize
        type: int
        value: 90
      notify: Restart Dock

    - name: Hide recent applications in Dock
      osx_defaults:
        domain: com.apple.dock
        key: show-recents
        type: int
        value: 0
      notify: Restart Dock

    - name: Enable App Exposé gesture
      osx_defaults:
        domain: com.apple.dock
        key: showAppExposeGestureEnabled
        type: int
        value: 1
      notify: Restart Dock

    - name: Disable natural scroll direction
      osx_defaults:
        domain: NSGlobalDomain
        key: com.apple.swipescrolldirection
        type: int
        value: 0
      notify: Restart Dock

  when: configure_macos_preferences | default(true)

# =============================================================================
# Start Services
# =============================================================================

- name: Start aerospace
  command: aerospace reload-config
  when: macos_window_manager == "aerospace" and aerospace_config.stat.exists
  ignore_errors: yes

- name: Display macOS tools installation status
  debug:
    msg: |
      macOS-specific tools installed successfully!

      ✅ Homebrew: Installed
      {% if macos_window_manager == "aerospace" %}
      ✅ AeroSpace: Tiling window manager
         - Config: ~/.config/aerospace/aerospace.toml
         - Reload config: aerospace reload-config
         - Start at login enabled
      {% endif %}
      {% if macos_menu_bar == "ice" %}
      ✅ Ice Bar: Menu bar manager
         - Launch Ice from Applications
         - Configure via menu bar icon
      {% endif %}
      {% if brewfile_exists.stat.exists %}
      ✅ Brewfile packages installed from {{ brewfile_path }}
      {% endif %}
      {% if configure_macos_preferences | default(true) %}
      ✅ macOS Dock preferences configured:
         - Position: Left side
         - Autohide: Enabled
         - Minimize effect: Suck
         - Magnification: Enabled (32px → 90px)
         - Recent apps: Hidden
         - Natural scroll: Disabled
      {% endif %}

      Next steps:
      1. Launch Ice Bar from Applications
      2. Configure Ice Bar settings (hide menu bar items, etc.)
      3. AeroSpace is running and managing windows
      4. Use Cmd+1, Cmd+2, etc. to switch workspaces
      5. Dock preferences have been applied (logout/login to see all changes)

      Your macOS development environment is ready! 🚀
