# shellcheck shell=bash
# Custom Tmux Powerline Theme
# Based on default theme with customizations

if patched_font_in_use; then
	TMUX_POWERLINE_SEPARATOR_LEFT_BOLD=""
	TMUX_POWERLINE_SEPARATOR_LEFT_THIN=""
	TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD=""
	TMUX_POWERLINE_SEPARATOR_RIGHT_THIN=""
else
	TMUX_POWERLINE_SEPARATOR_LEFT_BOLD="◖"
	TMUX_POWERLINE_SEPARATOR_LEFT_THIN="☾"
	TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD="◗"
	TMUX_POWERLINE_SEPARATOR_RIGHT_THIN="☽"
fi

# Force rounded powerline separators using Unicode escapes
TMUX_POWERLINE_SEPARATOR_LEFT_BOLD=$'\uE0B6'
TMUX_POWERLINE_SEPARATOR_LEFT_THIN=$'\uE0B7'
TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD=$'\uE0B4'
TMUX_POWERLINE_SEPARATOR_RIGHT_THIN=$'\uE0B5'

# Custom colors
TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR:-'230'}
TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR:-'237'}
# shellcheck disable=SC2034
TMUX_POWERLINE_SEG_AIR_COLOR=$(air_color)

TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD}
TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_LEFT_BOLD}

# Left status segments
# shellcheck disable=SC1143,SC2128
if [ -z "$TMUX_POWERLINE_LEFT_STATUS_SEGMENTS" ]; then
	TMUX_POWERLINE_LEFT_STATUS_SEGMENTS=(
		"tmux_session_info 142 229"
		"hostname 166 229"
		"pwd 172 229"
	)
fi

# Right status segments
# shellcheck disable=SC1143,SC2128
if [ -z "$TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS" ]; then
	TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS=(
		"load 237 167"
		"date_day 235 136"
		"date 235 136 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}"
		"time 235 136 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}"
	)
fi
