wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [60, 60, 60, 80]
    rows: [4, 4, 6, 4, 4, 6, 4 ,4, 6, 3]
  refreshInterval: 1
  mods:
    docker:
      type: docker
      enabled: true
      labelColor: lightblue
      position:
        top: 0
        left: 0
        height: 6
        width: 2
      refreshInterval: 1s
    hackernews:
      enabled: true
      numberOfStories: 26
      position:
        top: 0
        left: 2
        height: 6
        width: 2
      storyType: top
      refreshInterval: 15m
    ipapi:
      colors:
        name: red
        value: white
      # Optional  
      args:
        - "ip"
        - "isp"
        - "as"
        - "city"
        - "regionName"
        - "country"
        - "continent"
        - "coordinates"
        - "organization"
        - "timezone"
        - "reverseDNS"
      enabled: true
      position:
        top: 6
        left: 0
        height: 4
        width: 2
      refreshInterval: 150s
    power:
      enabled: true
      position:
        top: 6
        left: 2
        height: 4
        width: 2
      refreshInterval: 15
      title: "⚡️"
    uptime:
      args: [""]
      cmd: "uptime"
      enabled: true
      position:
        top: 10
        left: 0
        height: 1
        width: 4
      refreshInterval: 30
      type: cmdrunner
