#!/bin/bash

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

MAIN_COLOR=0xFF1e1e2e
BACKGROUND_COLOR=0x403b3b3b
ITEM_BACKGROUND_COLOR=0x36000000
ACCENT_COLOR=0xFFFFBF00
LIGHT_COLOR=0xFFFFFFFF

RADIUS=3
HEIGHT=24
BACKGROUND_ITEM_HEIGHT=18
TEXT_FONT="JetbrainsMono NF"
TEXT_FONT_SIZE="12.0"
TEXT_FONT_STYLE="Bold"
ICONS_FONT=${TEXT_FONT}
ICONS_FONT_SIZE="14.0"
ICONS_FONT_STYLE="Bold"
