---
# =============================================================================
# tmux Installation and Configuration
# =============================================================================

- name: Install tmux (macOS)
  homebrew:
    name: tmux
    state: present
  when: ansible_os_family == "Darwin"
  become: false

- name: Install tmux (Debian/Ubuntu)
  apt:
    name: tmux
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
  become: true

- name: Install tmux (Fedora/RHEL)
  dnf:
    name: tmux
    state: present
  when: ansible_os_family == "RedHat"
  become: true

- name: Ensure tmux config directory exists
  file:
    path: "{{ ansible_user_dir }}/.config/tmux"
    state: directory
    mode: '0755'

- name: Ensure tmux plugins directory exists
  file:
    path: "{{ ansible_user_dir }}/.config/tmux/plugins"
    state: directory
    mode: '0755'

- name: Clone TPM (Tmux Plugin Manager)
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_user_dir }}/.config/tmux/plugins/tpm"
    version: master
    update: yes

- name: Ensure tmux resurrect directory exists
  file:
    path: "{{ ansible_user_dir }}/.config/tmux/resurrect"
    state: directory
    mode: '0755'

- name: Install tmux plugins via TPM
  command: "{{ ansible_user_dir }}/.config/tmux/plugins/tpm/bin/install_plugins"
  args:
    creates: "{{ ansible_user_dir }}/.config/tmux/plugins/tmux-powerline"
  environment:
    TMUX_PLUGIN_MANAGER_PATH: "{{ ansible_user_dir }}/.config/tmux/plugins/"

- name: Check if tmux is running
  command: pgrep tmux
  register: tmux_running
  failed_when: false
  changed_when: false

- name: Display tmux installation status
  debug:
    msg: |
      tmux installed successfully!

      ✅ TPM (Tmux Plugin Manager) installed
      ✅ tmux plugins installed:
         - tmux-sensible (sensible defaults)
         - tmux-powerline (enhanced status line)
         - tmux-resurrect (session persistence)
         - tmux-continuum (automatic session saving)

      Your tmux.conf is ready with:
      - Prefix key: Ctrl+Space
      - Pane navigation: prefix + h/j/k/l
      - Session resurrection: automatic on startup

      {% if tmux_running.rc == 0 %}
      ⚠️  tmux is currently running. To see changes:
         - Reload config in tmux: Ctrl+Space then : source-file ~/.config/tmux/tmux.conf
         - Or restart tmux sessions
      {% else %}
      Start tmux: tmux
      {% endif %}
